### ISSUE TITLE
Expression handling in .Net Core 3.0

### ISSUE THREAD

**Issue by GitHubAre** [scottksmith95/LINQKit#105]
Hello,

I am in progress of upgrading to Asp.Net Core 3.0.
In previous version (2.2) this was working:
``` c#
private Expression<Func<AzureVm, bool>> SubscriptionFilter(string subscriptionName) =>
	vm => vm.SubscriptionName == subscriptionName;

public IEnumerable<AzureVm> GetVmsWithRelatedData(string subscription)
{
  return this.Query()
    .Include(vm => vm.AzureScaleSet)
    .Include(vm => vm.AzureVmTags)
    .Include(vm => vm.StartAndStopRecords)
    .Where(vm => SubscriptionFilter(subscription).Invoke(vm) && vm.AzureScaleSet == null)
    .Select();
}
```

In 3.0 it results to:
```
System.InvalidOperationException : The LINQ expression 'Where<TransparentIdentifier<AzureVm, AzureScaleSet>>(
    source: LeftJoin<AzureVm, AzureScaleSet, Nullable<int>, TransparentIdentifier<AzureVm, AzureScaleSet>>(
        outer: DbSet<AzureVm>, 
        inner: DbSet<AzureScaleSet>, 
        outerKeySelector: (a) => Property<Nullable<int>>(a, "AzureScaleSetId"), 
        innerKeySelector: (a0) => Property<Nullable<int>>(a0, "Id"), 
        resultSelector: (o, i) => new TransparentIdentifier<AzureVm, AzureScaleSet>(
            Outer = o, 
            Inner = i
        )), 
    predicate: (a) => Invoke<AzureVm, bool>(
        expr: (vm) => vm.SubscriptionName == (Unhandled parameter: __subscriptionName_0), 
        arg1: a.Outer) && Property<Nullable<int>>(a.Inner, "Id") == null)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
```

Is it because LinqKit is not compatible with Ef Core 3.0?

**Comment by StefH** [comment]
Some questions for you:

1]
what happens in your EFCore 2.x when you apply this change as described here: https://docs.microsoft.com/en-us/ef/core/querying/client-eval#previous-versions

2]
Shouldn't the query use `AsExpandable()` ?
Like:
``` c#
return this.Query()
    .AsExpandable()
    .Include(vm => vm.AzureScaleSet)
    .Include(vm => vm.AzureVmTags)
    .Include(vm => vm.StartAndStopRecords)
    .Where(vm => SubscriptionFilter(subscription).Invoke(vm) && vm.AzureScaleSet == null)
    .Select();
```

**Comment by GitHubAre** [comment]
I got your point and you are right, it was evaluated on the client side all the time. So when I did the https://docs.microsoft.com/en-us/ef/core/querying/client-eval#previous-versions, it throws exception.

Regarding second point, where I am trying to fix it so that its translated into SQL and evaluated in the database.
I have changed it to:
```
return this.Expandable()
                .Include(vm => vm.AzureScaleSet)
                .Include(vm => vm.AzureVmTags)
                .Include(vm => vm.StartAndStopRecords)
                .Where(vm => SubscriptionFilter(subscription).Invoke(vm) && vm.AzureScaleSet == null)
                .ToList();
```
Expandable() is my method inside repository class and it returns Set from DbContext:
```
public Repository(DbContext context)
{
    Context = context;
    Set = context.Set<TEntity>();
}

protected DbContext Context { get; }
protected DbSet<TEntity> Set { get; }
public IQueryable<TEntity> Expandable() => Set.AsExpandable();
```
I get this exception when executing the query:
System.InvalidCastException: 'Unable to cast object of type 'System.Linq.Expressions.InstanceMethodCallExpression1' to type 'System.Linq.Expressions.LambdaExpression'.'

**Comment by GitHubAre** [comment]
This was using .net core 2.2 and stack trace is:
```
System.InvalidCastException : Unable to cast object of type 'System.Linq.Expressions.InstanceMethodCallExpression1' to type 'System.Linq.Expressions.LambdaExpression'.
   at LinqKit.ExpressionExpander.VisitMethodCall(MethodCallExpression m)
   at LinqKit.ExpressionVisitor.VisitBinary(BinaryExpression b)
   at LinqKit.ExpressionVisitor.VisitLambda(LambdaExpression lambda)
   at LinqKit.ExpressionVisitor.VisitUnary(UnaryExpression u)
   at LinqKit.ExpressionVisitor.VisitExpressionList(ReadOnlyCollection`1 original)
   at LinqKit.ExpressionVisitor.VisitMethodCall(MethodCallExpression m)
   at LinqKit.ExpandableQueryProvider`1.System.Linq.IQueryProvider.CreateQuery[TElement](Expression expression)
   at System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)
   at Sws.ConfigurationProvider.Persistence.SwsAzure.Services.AzureVmService.GetVmsWithRelatedData(String subscription) in D:\Repos\toolbox\Common\03_csharp\Sws.ConfigurationProvider\Sws.ConfigurationProvider.Persistence\SwsAzure\Services\AzureVmService.cs:line 29
   at Sws.ConfigurationProvider.Tests.Persistence.ExploratoryTests.Test_GetVm_With_Related_Data() in D:\Repos\toolbox\Common\03_csharp\Sws.ConfigurationProvider\Sws.ConfigurationProvider.Tests\Persistence\ExploratoryTests.cs:line 47
```

**Comment by StefH** [comment]
Actually, I think your code should be (EF2.2 and EF3) like this:
``` c#
var result = TextualStatements.Query()
  .Where(SubscriptionFilter("TXT"))
  ToList();
```

No need to call invoke by yourself.

**Comment by GitHubAre** [comment]
I moved back to .Net Core 3.0 and error is different than in 2.2

Method 'ExecuteAsync' in type 'LinqKit.ExpandableQueryProvider`1' from assembly 'LinqKit.Microsoft.EntityFrameworkCore, Version=1.1.16.0, Culture=neutral, PublicKeyToken=a5e68054d5e7f94b' does not have an implementation.

I think its related to the Pull Request that is not yet released on Nuget.
For now I will rewrite the code and expand the expression in the .Where() and will try it later once its released as part of refactoring for more complex queries.
